<?php

use App\Enums\Ecosystem;
use App\Services\LockReader;

it('reads a classic (v1) yarn.lock with multi-descriptor blocks', function () {
    $lock = <<<'LOCK'
    # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

    lodash@^4.17.21:
      version "4.17.21"
      resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
      integrity sha512-x

    "@babel/core@^7.0.0", "@babel/core@^7.24.0":
      version "7.24.0"
      resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.0.tgz"
      integrity sha512-y

    eslint@^8.0.0:
      version "8.0.0"
      resolved "https://registry.yarnpkg.com/eslint/-/eslint-8.0.0.tgz"
      integrity sha512-z
    LOCK;

    $path = writeTempLock('yarn.lock', $lock);
    file_put_contents(dirname($path).'/package.json', json_encode([
        'dependencies' => ['lodash' => '^4.17.21', '@babel/core' => '^7.24.0'],
        'devDependencies' => ['eslint' => '^8.0.0'],
    ]));

    $packages = (new LockReader)->readYarn($path);
    $byName = collect($packages)->keyBy('name');

    expect($packages)->toHaveCount(3)
        ->and($byName['lodash']->current)->toBe('4.17.21')
        ->and($byName['lodash']->ecosystem)->toBe(Ecosystem::Npm)
        ->and($byName['lodash']->manager())->toBe('yarn')
        ->and($byName['lodash']->isDev)->toBeFalse()
        ->and($byName['@babel/core']->current)->toBe('7.24.0')
        ->and($byName['eslint']->isDev)->toBeTrue();
});

it('reads a berry (v2+) yarn.lock (YAML with npm: descriptors)', function () {
    $lock = <<<'LOCK'
    # This file is generated by running "yarn install"
    __metadata:
      version: 8
      cacheKey: 10

    "lodash@npm:^4.17.21":
      version: 4.17.21
      resolution: "lodash@npm:4.17.21"

    "@babel/core@npm:^7.0.0, @babel/core@npm:^7.24.0":
      version: 7.24.0
      resolution: "@babel/core@npm:7.24.0"
    LOCK;

    $packages = (new LockReader)->readYarn(writeTempLock('yarn.lock', $lock));
    $byName = collect($packages)->keyBy('name');

    expect($packages)->toHaveCount(2)
        ->and($byName['lodash']->current)->toBe('4.17.21')
        ->and($byName['lodash']->manager())->toBe('yarn')
        ->and($byName['@babel/core']->current)->toBe('7.24.0');
});
